version: "3.9" 
services:
  fibsrv:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - redis
    networks:
      - fibsrv-network

  redis:
    image: redis
    networks:
     fibsrv-network:
          aliases:
            - redis


networks:
  fibsrv-network:
    driver: "bridge"